apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-{{ .Values.studentId }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
      student: {{ .Values.studentId }}
  template:
    metadata:
      labels:
        app: juiceshop
        student: {{ .Values.studentId }}
    spec:
      containers:
        - name: juiceshop
          image: {{ .Values.image }}
          env:
            - name: NODE_ENV
              value: ctf
            - name: CTF_KEY
              value: {{ .Values.ctfKey | quote }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3