apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juiceshop-{{ .Values.studentId }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.namespace }}.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juiceshop-{{ .Values.studentId }}-svc
                port:
                  number: 3000
