name: CyberLabX CI

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - 'backend/**'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Helm lint
        run: helm lint k8s/juiceshop-lab

      - name: Helm template (render check)
        run: helm template test k8s/juiceshop-lab --set studentId=ci --set namespace=ci
